- CONTRIBUTING.md
- README.md
- src/Valleysoft.Dredge/DockerHubHelper.cs
- src/Valleysoft.Dredge/RepoCommand.cs
The original reason for making registry optional to the `repo list` command was to indicate a default registry of Docker Hub. But given that the Docker Hub registry doesn't support querying a repo list, there is no need to make this optional. Changing it to be a required argument.
> Set registry as required arg to "repo list" cmd

- src/Valleysoft.Dredge/ImageCommand.cs
The `image inspect` command doesn't support manifest list tags. It checks for that condition and throws an exception.
This change updates the behavior so that it resolves the manifest list to a matching platform from the list, based on the platform options that are provided by the caller. This allows the caller to specify the `os`, `os-version`, and `arch` options to help find the matching platform from the manifest list.
> Resolve manifest list to image for "image inspect" command

- src/Valleysoft.Dredge/ImageCommand.cs
- src/Valleysoft.Dredge/ImageName.cs
- src/Valleysoft.Dredge/ManifestCommand.cs
This adds a `manifest resolve` command which resolves a manifest name to a target platform, outputting a fully qualified digest value. This would primarily be used for resolving a manifest list to one of its underlying images, indicated by the options used to filter the platform: `os`, `arch`, `os-version`.
This also removes the same resolving functionality that previously existed in the `image inspect` command from https://github.com/mthalman/dredge/pull/17. The intent here is to have a standalone command that can be used to do this resolving behavior rather than integrating that behavior in all commands that it would be relevant to.
> Command to resolve a manifest to target platform

- src/Valleysoft.Dredge/ImageCommand.cs
- src/Valleysoft.Dredge/LinuxOsInfo.cs
- src/Valleysoft.Dredge/Valleysoft.Dredge.csproj
- src/Valleysoft.Dredge/WindowsOsInfo.cs
This new "image os" command allows a caller to output the OS information of the specified image. In the case of a Linux image, it will output the contents of the `os-release` file in a JSON format. For Windows, it will return back a JSON format consisting of a Type and Version field.
```
> dredge image os mcr.microsoft.com/dotnet/runtime@sha256:653251de361edf015e5ba8fd67e69543d3f32d91777cfdbf501bcab8aad5745b
{
"PRETTY_NAME": "Alpine Linux v3.16",
"NAME": "Alpine Linux",
"ID": "alpine",
"VERSION_ID": "3.16.2",
"HOME_URL": "https://alpinelinux.org/",
"BUG_REPORT_URL": "https://gitlab.alpinelinux.org/alpine/aports/-/issues"
}
```
```
> dredge image os mcr.microsoft.com/dotnet/runtime@sha256:ebefddf43d2d74decc311aebf417df3b231d2d8d8221261a940cd44a2e4d7d1f
{
"Type": "Server Core",
"Version": …
```
> Add "image os" command to output OS info of an image

- src/Valleysoft.Dredge/CompareLayersResult.cs
- src/Valleysoft.Dredge/CompareOutputFormat.cs
- src/Valleysoft.Dredge/ImageCommand.cs
- src/Valleysoft.Dredge/Valleysoft.Dredge.csproj
This "image compare layers" command allows you to compare the layer digests of two images.
There are a variety of output options available:
* SideBySide (default): Displays the comparison side-by-side in a table layout
* Inline: Displays the comparison in an inline fashion
* JSON: Returns a JSON representation of the comparison, including summary analysis
There's also a `--history` option to include the layer history information associated with the given layer. This can provide helpful context for a layer digest to understand how it was derived.
By default, the comparison makes use of green and red colors to indicate differences. For accessibility purposes, you can choose to use the `--no-color` option which will disable the use of these colors and use textual means to indicate diffs …
> Defines "image compare layers" command

- src/Valleysoft.Dredge/CompareLayersResult.cs
- src/Valleysoft.Dredge/ImageCommand.cs
This updates the `--history` option of the ["image compare layers" command](https://github.com/mthalman/dredge/pull/20) to compare layer history in addition to the layer digests. Previously the option only included the history in the output but didn't actually participate in the comparison. This then also accounts for empty layers as well. So even if a Dockerfile had layer digests that were identical, if a difference existed in the history (such as a LABEL instruction), that would show as a diff.
> Change history option to compare layer history

- src/Valleysoft.Dredge/ImageName.cs
Commands that accept an image name should allow an implicit `latest` tag if no tag is specified with the repo name. This wasn't handled properly, causing commands to attempt to query the registry with an empty value for the tag, resulting in a 404.
This is fixed by automatically resolving a missing tag value to `latest`.
> Fix implicit latest tag handling

- src/Valleysoft.Dredge/ImageCommand.cs
The `SideBySide` format for image layer comparison was not using the correct foreground color of the history row for the target image. In cases where it should have been green, it was showing red. This was due to not indicating the state correctly for whether the row represented the base image or not.
Before fix:
After fix:
> Fixes incorrect color for history row in sxs comparison

- src/Valleysoft.Dredge.Tests/CompareLayersCommandTests.cs
- src/Valleysoft.Dredge/CompareFilesOutput.cs
- src/Valleysoft.Dredge/CompareLayersOutput.cs
- src/Valleysoft.Dredge/DockerRegistryClientFactory.cs
- src/Valleysoft.Dredge/ImageCommand.cs
- src/Valleysoft.Dredge/Settings.cs
- src/Valleysoft.Dredge/Valleysoft.Dredge.csproj
Adds an `image compare files` command that provides a way to compare the file contents of two images. 
Example usage:
```shell
dredge image compare files amd64/node:19.1-alpine amd64/node:19.2-alpine
```
The layers of the images are downloaded and applied (squashed) to produce a local representation of the file system for each image.
The actual comparison of the files requires an external tool provided by the user. This external comparison tool is configured with Dredge's settings.json file.
Example:
```json
{
"fileCompareTool": {
"exePath": "C:\\Program Files\\Beyond Compare 4\\BCompare.exe",
"args": "{0} {1}"
}
}
```
In addition to comparing the entire image, you can also include a subset of the image by specifying a layer index in the command options. This will only apply the layers of …
> Adds "image compare files" command

- src/Valleysoft.Dredge/Program.cs
- src/Valleysoft.Dredge/SettingsCommand.cs
Adds a `settings` command which opens the `settings.json` file in the default associated program associated. If unable to do so, it outputs the path of the file.
> Add a settings command

- .github/workflows/release.yml
Supports standalone executables for MacOS by including the osx RID for both x64 and arm64.
Also updates the target version to .NET 7.
> Support MacOS standalone executables

- src/Valleysoft.Dredge/FileHelper.cs
- src/Valleysoft.Dredge/ImageCommand.cs
Adds a new `image save-layers` command which saves the layers of an image to disk. The tarballs of the layers are extracted. By default, the layers are squashed to have one applied file system. There is a `--no-squash` option that will save each layer in its own separate directory. In addition, the `--layer-index` option allows you to target a specific layer of the image.
> Adds "image save-layers" command

- src/Valleysoft.Dredge/ClearCacheCommand.cs
- src/Valleysoft.Dredge/DredgeState.cs
- src/Valleysoft.Dredge/ImageCommand.cs
- src/Valleysoft.Dredge/Program.cs
- src/Valleysoft.Dredge/SettingsCommand.cs
The `clear-cache` command provides a way to delete the temporary cache directory used by Dredge.
> Adds "clear-cache" command

- src/Valleysoft.Dredge/DockerRegistryClientFactory.cs
If an attempt is made to use Dredge without having Docker installed, it results in a `FileNotFoundException` because the `<username>/.docker/config.json` file does not exist. An attempt is made to access this file by DockerCredsProvider which is part of the default behavior of Dredge in order to pick up any ambient registry creds.
To avoid requiring this file to exist, the fix is to simply handle this `FileNotFoundException` and default to no credentials in that case.
> Support no Docker installation

- src/Valleysoft.Dredge/ImageCommand.cs
The logic for extracting a layer tarball didn't handle the existence of an empty directory. It relied on there being a file in a directory to actually create the directory.
> Support tarball extraction with empty directory

- .github/workflows/release.yml
Adds a `latest` tag for publishing Docker images.
> Include latest tag for image publish

- .github/workflows/release.yml
- src/Valleysoft.Dredge/Dockerfile
- src/Valleysoft.Dredge/Valleysoft.Dredge.csproj
Because of the changes to add publish properties into the csproj, the `dotnet pack` command is failing because it thinks things are configured for self-contained which it doesn't support.
Updated the csproj to conditional set the publish properties.
> Fix pack and publish

- src/Valleysoft.Dredge.Tests/CompareLayersCommandTests.cs
- src/Valleysoft.Dredge/CompareLayersResult.cs
- src/Valleysoft.Dredge/ImageCommand.cs
This adds a new `--compressed-size` option to the `image compare layers` command. This will include the compressed size of the layers in the output.
> Add compressed-size option for comparing layers

- src/Valleysoft.Dredge.Tests/DockerfileCommandTests.cs
- src/Valleysoft.Dredge/Commands/Image/CompareFilesCommand.cs
- src/Valleysoft.Dredge/Commands/Image/CompareLayersCommand.cs
- src/Valleysoft.Dredge/Commands/Image/CompareOptionsBase.cs
- src/Valleysoft.Dredge/Commands/Image/DockerfileCommand.cs
- src/Valleysoft.Dredge/Commands/Image/DockerfileOptions.cs
- src/Valleysoft.Dredge/Commands/Image/InspectCommand.cs
- src/Valleysoft.Dredge/Commands/Image/InspectOptions.cs
- src/Valleysoft.Dredge/Commands/Image/OsCommand.cs
- src/Valleysoft.Dredge/Commands/Image/OsOptions.cs
- src/Valleysoft.Dredge/Commands/Image/SaveLayersCommand.cs
- src/Valleysoft.Dredge/Commands/Image/SaveLayersOptions.cs
- src/Valleysoft.Dredge/Commands/Manifest/ResolveCommand.cs
- src/Valleysoft.Dredge/Commands/Manifest/ResolveOptions.cs
- src/Valleysoft.Dredge/Commands/PlatformOptionsBase.cs
- src/Valleysoft.Dredge/ImageHelper.cs
- src/Valleysoft.Dredge/ManifestHelper.cs
This adds the following platform options that will be used to resolve a reference manifest list to an underlying manifest:
* os
* os-version
* arch
These are the same options that already existed for the `manifest resolve` command. But they're now applied to all commands that need to operate on an actual image, allowing the caller to use a multi-arch tag if they choose so and specifying the options to resolve it.
> Include platform options for all commands referencing an image

- src/Valleysoft.Dredge/AppSettings.cs
- src/Valleysoft.Dredge/Commands/CommandWithOptions.cs
- src/Valleysoft.Dredge/Commands/Image/CompareFilesCommand.cs
- src/Valleysoft.Dredge/Commands/Image/CompareLayersCommand.cs
- src/Valleysoft.Dredge/Commands/Image/DockerfileCommand.cs
- src/Valleysoft.Dredge/Commands/Image/InspectCommand.cs
- src/Valleysoft.Dredge/Commands/Image/OsCommand.cs
- src/Valleysoft.Dredge/Commands/Image/SaveLayersCommand.cs
- src/Valleysoft.Dredge/Commands/Manifest/DigestCommand.cs
- src/Valleysoft.Dredge/Commands/Manifest/GetCommand.cs
- src/Valleysoft.Dredge/Commands/Manifest/ResolveCommand.cs
- src/Valleysoft.Dredge/Commands/Manifest/ResolveOptions.cs
- src/Valleysoft.Dredge/Commands/OptionsBase.cs
- src/Valleysoft.Dredge/Commands/RegistryCommandBase.cs
- src/Valleysoft.Dredge/Commands/Repo/ListCommand.cs
- src/Valleysoft.Dredge/Commands/Settings/GetCommand.cs
- src/Valleysoft.Dredge/Commands/Settings/GetOptions.cs
- src/Valleysoft.Dredge/Commands/Settings/SetCommand.cs
- src/Valleysoft.Dredge/Commands/Settings/SetOptions.cs
- src/Valleysoft.Dredge/Commands/Settings/SettingsCommand.cs
- src/Valleysoft.Dredge/Commands/Tag/ListCommand.cs
- src/Valleysoft.Dredge/Program.cs
Adds a `settings get` and `settings set` command to allow callers to retrieve and set the values of settings.
Because the settings in the settings file are hierarchical and represented as JSON, setting names use a dot-notation to separate the names to access the desired setting. For example: `dredge settings get fileCompareTool.exePath` gets the executable path of the file compare tool from the settings file.
Usage:
```
dredge settings get <name>
```
```
dredge settings set <name> <value>
```
> Add get/set commands for settings

- src/Valleysoft.Dredge/AppSettings.cs
- src/Valleysoft.Dredge/Commands/Image/CompareLayersCommand.cs
- src/Valleysoft.Dredge/Commands/Image/DockerfileCommand.cs
- src/Valleysoft.Dredge/Commands/Image/InspectCommand.cs
- src/Valleysoft.Dredge/Commands/Image/OsCommand.cs
- src/Valleysoft.Dredge/Commands/Image/SaveLayersCommand.cs
- src/Valleysoft.Dredge/Commands/Manifest/ResolveCommand.cs
- src/Valleysoft.Dredge/Commands/PlatformOptionsBase.cs
- src/Valleysoft.Dredge/ImageHelper.cs
- src/Valleysoft.Dredge/ManifestHelper.cs
With these changes the Dredge settings file can be configured with platform settings that define the default platform configuration to use when needing to result a manifest list.
The settings file has this configuration:
```json
{
"platform": {
"os": "<os-name>",
"osVersion": "<os-version>",
"arch": "<architecture>"
}
}
```
When any one of these platform values is set, it influences the logic taken in order to resolve a manifest list to an underlying manifest. For example, a call to `dredge image inspect alpine:latest` requires resolving the `latest` tag to an underlying image since `latest` is a manifest list (multi-arch tag).
If the settings file was set as the following:
```json
{
"platform": {
"os": "linux",
"osVersion": "",
"arch": "amd64"
}
}
```
It would automatically resolve …
> Support for global platform settings

- src/Valleysoft.Dredge/Commands/Image/CompareFilesOptions.cs
When running the `image compare files` command, it was always defaulting to comparing the first layer of the images. This is because the `base-layer-index` and `target-layer-index` were being defaulted to `0` instead of `null`.
> Fix compare files to not default to index 0

- src/Valleysoft.Dredge/FileHelper.cs
- src/Valleysoft.Dredge/ImageHelper.cs
An exception will occur when attempting to create a symlink on a Windows system that doesn't have Developer Mode enabled. This provides a better error message to the user to let them know.
> Add symlink error handling

- src/Valleysoft.Dredge/ImageHelper.cs
For some images, there can be a blob layer which doesn't have any content. This is a good example of this: https://github.com/dotnet/dotnet-docker/blob/f6ec771805d726e08327ce123893f8924539ff90/src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile#L54. For such a layer, there's no new content being added but it's still a layer that gets processed.
This currently isn't handled correctly because no files get written to the layers cache directory. That causes a directory not found exception when applying layers.
This is fixed by simply ensuring the layer directory is created.
> Ensure layer dir is created

- .github/workflows/release.yml
- src/Valleysoft.Dredge/Valleysoft.Dredge.csproj
When generating a NuGet package, the package needs portable assets. But the default publish options in the project make it RID-specific and generally not what is needed for a portable package. This updates the project config to only use those settings outside the context of generating a package.
> Exclude publish options when generating package

- .github/workflows/docker-publish.yml
- .github/workflows/init.yml
- .github/workflows/release.yml
This factors out Docker publishing into a reusable workflow so that it can be executed independently of the overall release workflow. This allows for rebuilding of the image outside the context of releases, so that base image updates can be incorporated.
> Refactor workflows into reusable parts

- .github/workflows/release.yml
- src/Dockerfile
- src/Valleysoft.Dredge/Valleysoft.Dredge.csproj
To better utilize shared installation of .NET, I'm switching from a self-contained deployment to framework-dependent deployment. This will require an existing installation of the .NET runtime in order to run the executable.
> Switch to framework-dependent deployment

- src/Valleysoft.Dredge/Commands/Image/CompareLayersCommand.cs
- src/Valleysoft.Dredge/CompareLayersResult.cs
This changes the schema of the output of the `image compare layers` command when outputting as JSON. It now uses camelCasing instead of PascalCasing. It also accordingly adjusts the values of the `layerDiff` field (e.g. `Equal` => `equal`, `Not Equal` => `notEqual`).
> Change diff JSON output to use camelCasing

- src/Valleysoft.Dredge/CommandHelper.cs
This fixes an issue where dredge would always return an exit code of 0, even when an error occurred.
> Ensure non-zero exit code on error

- docs/commands/referrers.md
- src/Valleysoft.Dredge/Commands/Referrer/ListCommand.cs
- src/Valleysoft.Dredge/Commands/Referrer/ListOptions.cs
- src/Valleysoft.Dredge/Commands/Referrer/ReferrerCommand.cs
- src/Valleysoft.Dredge/DockerRegistryClientWrapper.cs
- src/Valleysoft.Dredge/IDockerRegistryClient.cs
- src/Valleysoft.Dredge/Program.cs
- src/Valleysoft.Dredge/Valleysoft.Dredge.csproj
This provides a command which queries the [referrers](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers) API to find artifacts that refer to the specified manifest.
> Command to list referrers of a manifest

- src/Valleysoft.Dredge/Commands/Image/OsCommand.cs
Some Linux distros, such as CBL-Mariner, have their `os-release` path defined as `./etc/os-release` instead of just `etc/os-release`. Updated the logic to handle either case.
> Handle variations in os-release path

- .github/workflows/release.yml
The build is failing with:
```
Run dotnet publish -f net9.0 -c Release -p:Version=$PACKAGE_VERSION --no-restore -o /home/runner/work/dredge/dredge/publish --runtime osx-x64 --no-self-contained
/usr/share/dotnet/sdk/9.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(22[6](https://github.com/mthalman/dredge/actions/runs/12733865223/job/35490727565#step:5:7),5): error MSB4044: The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion". [/home/runner/work/dredge/dredge/src/Valleysoft.Dredge.Analyzers/Valleysoft.Dredge.Analyzers.csproj::TargetFramework=netstandard2.0]
```
This is a regression caused by https://github.com/mthalman/dredge/pull/137 because it doesn't have `PACKAGE_VERSION` set. Related to …
> Flow product-version to build/publish
